Repository aragon/aragon-wiki, pull requests merged in 2018-02, with the labels that each got.

#159 Added blog posts for Feb 2018 thru current day
  docs/blog/2018.md
Labels: enhancement

#172 Add Jouni interview
  docs/blog/2018.md
Labels: enhancement

#176 Add ETHDenver recap blog post
  docs/blog/2018.md
Labels: enhancement

#183 Create john.md
  docs/meetings/community/write-ups/cm09/john.md
Labels: Community Meeting Write-Up

#184 Add Jorge cm09 write-up
  docs/meetings/community/write-ups/cm09/jorge.md
Labels: Community Meeting Write-Up

#175 Create CM meeting 09 agenda
  docs/meetings/community/09.md
Labels: documentation

#186 Update Building DAOs initiative
  docs/meetings/community/write-ups/cm09/john.md
Labels: enhancement
