Repository aragon/aragon-wiki, pull requests merged in 2018-04, with the labels that each got.

#211 Add write-up for CM10: ßingen
  docs/meetings/community/write-ups/cm10/bingen.md
  mkdocs.yml
Labels: Community Meeting Write-Up

#212 Add Jorge cm10 write-up
  docs/meetings/community/write-ups/cm09/jorge.md
  docs/meetings/community/write-ups/cm10/jorge.md
  mkdocs.yml
Labels: Community Meeting Write-Up

#215 Create light.md
  docs/meetings/community/write-ups/cm10/light.md
Labels: Community Meeting Write-Up

#216 Add CM10 write-up for Maria
  docs/meetings/community/write-ups/cm10/maria.md
Labels: Community Meeting Write-Up

#217 add tatucm10 write-up
  docs/meetings/community/write-ups/cm10/tatu.md
Labels: Community Meeting Write-Up

#218 Adding writeup for cm10
  docs/meetings/community/write-ups/cm10/luis.md
Labels: Community Meeting Write-Up

#210 Add Chris Remus team interview & v0.5 release post
  docs/blog/2018.md
Labels: documentation

#220 Create chris.md
  docs/meetings/community/write-ups/cm10/chris.md
Labels: Community Meeting Write-Up

#222 Create CM 10 agenda
  docs/meetings/community/10.md
Labels: documentation

#223 Add YT link and time of CM
  docs/meetings/community/10.md
Labels: documentation

#226 Update chris.md
  docs/meetings/community/write-ups/cm10/chris.md
Labels: Community Meeting Write-Up

#227 Add March update blog post
  docs/blog/2018.md
Labels: documentation

#228 Fix video link
  docs/meetings/community/10.md
Labels: documentation

#229 Create user_guide folder
  docs/images/user_guide/createfolder.md
Labels: documentation

#230 upload user guide images
  docs/images/user_guide/choosedemo.png
  docs/images/user_guide/chooseorg.png
  docs/images/user_guide/daoaddmember.png
  docs/images/user_guide/daoaddmemberapprove.png
  docs/images/user_guide/daoaddmembervote.png
  docs/images/user_guide/daoaddmembervotesign.png
  docs/images/user_guide/daofinance.png
  docs/images/user_guide/daofinancereview.png
  docs/images/user_guide/daohome.png
  docs/images/user_guide/daomm1.png
  docs/images/user_guide/daonewtransfer.png
  docs/images/user_guide/daonewtransfersign.png
  docs/images/user_guide/daonewtransfervote.png
  docs/images/user_guide/daonewvote.png
  docs/images/user_guide/daonewvoteno.png
  docs/images/user_guide/daonewvotesign.png
  docs/images/user_guide/daonewvotestalemate.png
  docs/images/user_guide/daoready.png
  docs/images/user_guide/daosettings1.png
  docs/images/user_guide/daosettings2.png
  docs/images/user_guide/daotokenmanager.png
  docs/images/user_guide/daotokens.png
  docs/images/user_guide/daotransferpass.png
  docs/images/user_guide/daotransfervotesign.png
  docs/images/user_guide/daoviewvote.png
  docs/images/user_guide/daovoting.png
  docs/images/user_guide/democracysettings.png
  docs/images/user_guide/noorg.png
  docs/images/user_guide/orgready.png
  docs/images/user_guide/thedaoname.png
  docs/images/user_guide/votescreen.png
  docs/images/user_guide/voting.png
  docs/images/user_guide/welcome.png
Labels: documentation

#232 Add community meetings 8-10
  docs/videos/community.md
Labels: documentation

#235 Add Dao workshop tutorial
  docs/documentation/tutorials/DAO_Workshop_Testnet_by_joselfgaray.md
  docs/tutorials/DAO_Workshop_Testnet_by_joselfgaray.md
  docs/tutorials/images/dao_workshop01.png
  docs/tutorials/images/dao_workshop02.png
  docs/tutorials/images/dao_workshop03.png
  docs/tutorials/images/dao_workshop04.png
  docs/tutorials/images/dao_workshop05.png
  docs/tutorials/images/dao_workshop06.png
  docs/tutorials/images/dao_workshop07.png
  docs/tutorials/images/dao_workshop08.png
  docs/tutorials/images/dao_workshop09.png
  docs/tutorials/images/dao_workshop10.png
  docs/tutorials/images/dao_workshop11.png
  docs/tutorials/images/dao_workshop12.png
  docs/tutorials/images/dao_workshop13.png
  docs/tutorials/images/dao_workshop14.png
  docs/tutorials/images/dao_workshop15.png
  docs/tutorials/images/dao_workshop16.png
  docs/tutorials/images/dao_workshop17.png
  docs/tutorials/images/dao_workshop18.png
  docs/tutorials/images/dao_workshop19.png
  docs/tutorials/images/dao_workshop20.png
  docs/tutorials/images/dao_workshop21.png
  docs/tutorials/images/dao_workshop22.png
  docs/tutorials/images/dao_workshop23.png
  docs/tutorials/images/dao_workshop_fight_for_freedom.png
  mkdocs.yml
Labels: doc: app guide, documentation, tutorial

#239 Create CM11 agenda doc
  docs/meetings/community/11.md
Labels: documentation

#240 Add CM meeting 11
  docs/videos/community.md
Labels: documentation
