Repository aragon/aragon-wiki, pull requests merged in 2018-09, with the labels that each got.

#330 Add TPS interview
  docs/blog/2018.md
Labels: documentation

#335 add glossary & event policy, small fixes
  docs/design/logo/aragoncli/aragoncli-horizontal.png
  docs/design/logo/aragoncli/aragoncli-vertical.png
  docs/design/logo/aragonjs/aragonjs-horizontal.png
  docs/design/logo/aragonjs/aragonjs-vertical.png
  docs/design/logo/aragonos/aragonos-horizontal.png
  docs/design/logo/aragonos/aragonos-vertical.png
  docs/design/logo/aragonpm/aragon-package-manager-horizontal.png
  docs/design/logo/aragonpm/aragon-package-manager-vertical.png
  docs/design/logo/png/.directory
  docs/documentation/event_policy.md
  docs/documentation/glossary.md
  docs/index.md
  docs/jobs/index.md
  mkdocs.yml
Labels: documentation, enhancement

#328 Add All Core Devs section to mkdocs.yml
  docs/videos/dev.md
  docs/videos/template.md
  mkdocs.yml
Labels: documentation

#331 Add recent blog posts
  docs/blog/2018.md
Labels: documentation

#337 Update website URL and add research forum link
  docs/index.md
Labels: enhancement

#341 Add Humanist Blockchain Future interview
  docs/videos/interviews.md
Labels: documentation

#340 Add link to Powered By Aragon guidelines page
  docs/projects/index.md
Labels: enhancement

#342 Add APM blog post
  docs/blog/A1/2018.md
Labels: documentation

#338 Add Manifesto to wiki
  docs/design/artwork/ANT/.directory
  docs/design/artwork/basic/.directory
  docs/documentation/manifesto.md
  mkdocs.yml
Labels: documentation
